// This file is autogenerated by the hrpc compiler
/* eslint-disable camelcase */
/* eslint-disable space-before-function-paren */

import { c, RPC, RPCStream, RPCRequestStream } from 'hrpc/runtime'
import { getEncoding } from './messages.js'

const methods = new Map([
  ['@opennib/init', 0],
  [0, '@opennib/init'],
  ['@opennib/shutdown', 1],
  [1, '@opennib/shutdown'],
  ['@opennib/transcriber-preload', 2],
  [2, '@opennib/transcriber-preload'],
  ['@opennib/transcribe', 3],
  [3, '@opennib/transcribe'],
  ['@opennib/transcriber-unload-all', 4],
  [4, '@opennib/transcriber-unload-all'],
  ['@opennib/transcribe-file', 5],
  [5, '@opennib/transcribe-file'],
  ['@opennib/model-load', 6],
  [6, '@opennib/model-load'],
  ['@opennib/cleaner-configure', 7],
  [7, '@opennib/cleaner-configure'],
  ['@opennib/cleaner-cleanup', 8],
  [8, '@opennib/cleaner-cleanup'],
  ['@opennib/history-append', 9],
  [9, '@opennib/history-append'],
  ['@opennib/history-list', 10],
  [10, '@opennib/history-list'],
  ['@opennib/history-clear', 11],
  [11, '@opennib/history-clear'],
  ['@opennib/dictionary-list', 12],
  [12, '@opennib/dictionary-list'],
  ['@opennib/dictionary-add', 13],
  [13, '@opennib/dictionary-add'],
  ['@opennib/dictionary-remove', 14],
  [14, '@opennib/dictionary-remove'],
  ['@opennib/dictionary-clear', 15],
  [15, '@opennib/dictionary-clear'],
  ['@opennib/model-progress', 16],
  [16, '@opennib/model-progress']
])

class HRPC {
  constructor(stream) {
    this._stream = stream
    this._handlers = []
    this._requestEncodings = new Map([
      ['@opennib/init', getEncoding('@opennib/init-request')],
      ['@opennib/shutdown', getEncoding('@opennib/empty')],
      ['@opennib/transcriber-preload', getEncoding('@opennib/preload-request')],
      ['@opennib/transcribe', getEncoding('@opennib/transcribe-request')],
      ['@opennib/transcriber-unload-all', getEncoding('@opennib/empty')],
      ['@opennib/transcribe-file', getEncoding('@opennib/transcribe-file-request')],
      ['@opennib/model-load', getEncoding('@opennib/model-load-request')],
      ['@opennib/cleaner-configure', getEncoding('@opennib/cleaner-configure-request')],
      ['@opennib/cleaner-cleanup', getEncoding('@opennib/cleanup-request')],
      ['@opennib/history-append', getEncoding('@opennib/history-append-request')],
      ['@opennib/history-list', getEncoding('@opennib/history-list-request')],
      ['@opennib/history-clear', getEncoding('@opennib/empty')],
      ['@opennib/dictionary-list', getEncoding('@opennib/empty')],
      ['@opennib/dictionary-add', getEncoding('@opennib/dictionary-entry')],
      ['@opennib/dictionary-remove', getEncoding('@opennib/dictionary-remove-request')],
      ['@opennib/dictionary-clear', getEncoding('@opennib/empty')],
      ['@opennib/model-progress', getEncoding('@opennib/model-progress')]
    ])
    this._responseEncodings = new Map([
      ['@opennib/init', getEncoding('@opennib/ack')],
      ['@opennib/shutdown', getEncoding('@opennib/ack')],
      ['@opennib/transcriber-preload', getEncoding('@opennib/ack')],
      ['@opennib/transcribe', getEncoding('@opennib/text-response')],
      ['@opennib/transcriber-unload-all', getEncoding('@opennib/ack')],
      ['@opennib/transcribe-file', getEncoding('@opennib/text-response')],
      ['@opennib/model-load', getEncoding('@opennib/ack')],
      ['@opennib/cleaner-configure', getEncoding('@opennib/ack')],
      ['@opennib/cleaner-cleanup', getEncoding('@opennib/text-response')],
      ['@opennib/history-append', getEncoding('@opennib/ack')],
      ['@opennib/history-list', getEncoding('@opennib/history-list-response')],
      ['@opennib/history-clear', getEncoding('@opennib/ack')],
      ['@opennib/dictionary-list', getEncoding('@opennib/dictionary-list-response')],
      ['@opennib/dictionary-add', getEncoding('@opennib/ack')],
      ['@opennib/dictionary-remove', getEncoding('@opennib/ack')],
      ['@opennib/dictionary-clear', getEncoding('@opennib/ack')]
    ])
    this._rpc = new RPC(stream, async (req) => {
      const command = methods.get(req.command)
      const responseEncoding = this._responseEncodings.get(command)
      const requestEncoding = this._requestEncodings.get(command)
      if (this._requestIsSend(command)) {
        const request = req.data ? c.decode(requestEncoding, req.data) : null
        await this._handlers[command](request)
        return
      }
      if (!this._requestIsStream(command) && !this._responseIsStream(command)) {
        const request = req.data ? c.decode(requestEncoding, req.data) : null
        const response = await this._handlers[command](request)
        req.reply(c.encode(responseEncoding, response))
      }
      if (!this._requestIsStream(command) && this._responseIsStream(command)) {
        const request = req.data ? c.decode(requestEncoding, req.data) : null
        const responseStream = new RPCStream(
          null,
          null,
          req.createResponseStream(),
          responseEncoding
        )
        responseStream.data = request
        await this._handlers[command](responseStream)
      }
      if (this._requestIsStream(command) && !this._responseIsStream(command)) {
        const requestStream = new RPCRequestStream(
          req,
          responseEncoding,
          req.createRequestStream(),
          requestEncoding
        )
        const response = await this._handlers[command](requestStream)
        req.reply(c.encode(responseEncoding, response))
      }
      if (this._requestIsStream(command) && this._responseIsStream(command)) {
        const requestStream = new RPCRequestStream(
          req,
          responseEncoding,
          req.createRequestStream(),
          requestEncoding,
          req.createResponseStream(),
          responseEncoding
        )
        await this._handlers[command](requestStream)
      }
    })
  }

  async _call(name, args) {
    const requestEncoding = this._requestEncodings.get(name)
    const responseEncoding = this._responseEncodings.get(name)
    const request = this._rpc.request(methods.get(name))
    const encoded = c.encode(requestEncoding, args)
    request.send(encoded)
    return c.decode(responseEncoding, await request.reply())
  }

  _callSync(name, args) {
    const requestEncoding = this._requestEncodings.get(name)
    const responseEncoding = this._responseEncodings.get(name)
    if (this._requestIsSend(name)) {
      const encoded = c.encode(requestEncoding, args)
      const request = this._rpc.event(methods.get(name))
      request.send(encoded)
    }

    const request = this._rpc.request(methods.get(name))

    if (!this._requestIsStream(name) && this._responseIsStream(name)) {
      const encoded = c.encode(requestEncoding, args)
      request.send(encoded)
      return new RPCStream(request.createResponseStream(), responseEncoding)
    }
    if (this._requestIsStream(name) && !this._responseIsStream(name)) {
      return new RPCRequestStream(
        request,
        responseEncoding,
        null,
        null,
        request.createRequestStream(),
        requestEncoding
      )
    }
    if (this._requestIsStream(name) && this._responseIsStream(name)) {
      return new RPCRequestStream(
        request,
        responseEncoding,
        request.createResponseStream(),
        responseEncoding,
        request.createRequestStream(),
        requestEncoding
      )
    }
  }

  async init(args) {
    return this._call('@opennib/init', args)
  }

  async shutdown(args) {
    return this._call('@opennib/shutdown', args)
  }

  async transcriberPreload(args) {
    return this._call('@opennib/transcriber-preload', args)
  }

  async transcribe(args) {
    return this._call('@opennib/transcribe', args)
  }

  async transcriberUnloadAll(args) {
    return this._call('@opennib/transcriber-unload-all', args)
  }

  async transcribeFile(args) {
    return this._call('@opennib/transcribe-file', args)
  }

  async modelLoad(args) {
    return this._call('@opennib/model-load', args)
  }

  async cleanerConfigure(args) {
    return this._call('@opennib/cleaner-configure', args)
  }

  async cleanerCleanup(args) {
    return this._call('@opennib/cleaner-cleanup', args)
  }

  async historyAppend(args) {
    return this._call('@opennib/history-append', args)
  }

  async historyList(args) {
    return this._call('@opennib/history-list', args)
  }

  async historyClear(args) {
    return this._call('@opennib/history-clear', args)
  }

  async dictionaryList(args) {
    return this._call('@opennib/dictionary-list', args)
  }

  async dictionaryAdd(args) {
    return this._call('@opennib/dictionary-add', args)
  }

  async dictionaryRemove(args) {
    return this._call('@opennib/dictionary-remove', args)
  }

  async dictionaryClear(args) {
    return this._call('@opennib/dictionary-clear', args)
  }

  modelProgress(args) {
    return this._callSync('@opennib/model-progress', args)
  }

  onInit(responseFn) {
    this._handlers['@opennib/init'] = responseFn
  }

  onShutdown(responseFn) {
    this._handlers['@opennib/shutdown'] = responseFn
  }

  onTranscriberPreload(responseFn) {
    this._handlers['@opennib/transcriber-preload'] = responseFn
  }

  onTranscribe(responseFn) {
    this._handlers['@opennib/transcribe'] = responseFn
  }

  onTranscriberUnloadAll(responseFn) {
    this._handlers['@opennib/transcriber-unload-all'] = responseFn
  }

  onTranscribeFile(responseFn) {
    this._handlers['@opennib/transcribe-file'] = responseFn
  }

  onModelLoad(responseFn) {
    this._handlers['@opennib/model-load'] = responseFn
  }

  onCleanerConfigure(responseFn) {
    this._handlers['@opennib/cleaner-configure'] = responseFn
  }

  onCleanerCleanup(responseFn) {
    this._handlers['@opennib/cleaner-cleanup'] = responseFn
  }

  onHistoryAppend(responseFn) {
    this._handlers['@opennib/history-append'] = responseFn
  }

  onHistoryList(responseFn) {
    this._handlers['@opennib/history-list'] = responseFn
  }

  onHistoryClear(responseFn) {
    this._handlers['@opennib/history-clear'] = responseFn
  }

  onDictionaryList(responseFn) {
    this._handlers['@opennib/dictionary-list'] = responseFn
  }

  onDictionaryAdd(responseFn) {
    this._handlers['@opennib/dictionary-add'] = responseFn
  }

  onDictionaryRemove(responseFn) {
    this._handlers['@opennib/dictionary-remove'] = responseFn
  }

  onDictionaryClear(responseFn) {
    this._handlers['@opennib/dictionary-clear'] = responseFn
  }

  onModelProgress(responseFn) {
    this._handlers['@opennib/model-progress'] = responseFn
  }

  _requestIsStream(command) {
    return [
    ].includes(command)
  }

  _responseIsStream(command) {
    return [
    ].includes(command)
  }

  // prettier-ignore-start
  _requestIsSend(command) {
    return [
      // prettier-ignore
      '@opennib/model-progress'
    ].includes(command)
  }
}

export default HRPC
