// This file is autogenerated by the hyperschema compiler
// Schema Version: 2
/* eslint-disable camelcase */
/* eslint-disable quotes */
/* eslint-disable space-before-function-paren */

import { c } from 'hyperschema/runtime'

const VERSION = 2

// eslint-disable-next-line no-unused-vars
let version = VERSION

// @opennib/rpc-error
const encoding0 = {
  preencode(state, m) {
    c.string.preencode(state, m.name)
    c.string.preencode(state, m.message)
  },
  encode(state, m) {
    c.string.encode(state, m.name)
    c.string.encode(state, m.message)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.string.decode(state)

    return {
      name: r0,
      message: r1
    }
  }
}

// @opennib/ack.error
const encoding1_0 = c.frame(encoding0)

// @opennib/ack
const encoding1 = {
  preencode(state, m) {
    state.end++ // max flag is 1 so always one byte

    if (m.error) encoding1_0.preencode(state, m.error)
  },
  encode(state, m) {
    const flags = m.error ? 1 : 0

    c.uint.encode(state, flags)

    if (m.error) encoding1_0.encode(state, m.error)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      error: (flags & 1) !== 0 ? encoding1_0.decode(state) : null
    }
  }
}

// @opennib/empty
const encoding2 = {
  preencode(state, m) {

  },
  encode(state, m) {

  },
  decode(state) {
    return {
    }
  }
}

// @opennib/transcript-entry
const encoding3 = {
  preencode(state, m) {
    c.string.preencode(state, m.id)
    c.uint.preencode(state, m.createdAt)
    c.string.preencode(state, m.text)
    c.string.preencode(state, m.language)
    c.uint.preencode(state, m.durationMs)
    state.end++ // max flag is 1 so always one byte

    if (m.app) c.string.preencode(state, m.app)
  },
  encode(state, m) {
    const flags = m.app ? 1 : 0

    c.string.encode(state, m.id)
    c.uint.encode(state, m.createdAt)
    c.string.encode(state, m.text)
    c.string.encode(state, m.language)
    c.uint.encode(state, m.durationMs)
    c.uint.encode(state, flags)

    if (m.app) c.string.encode(state, m.app)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.uint.decode(state)
    const r2 = c.string.decode(state)
    const r3 = c.string.decode(state)
    const r4 = c.uint.decode(state)
    const flags = c.uint.decode(state)

    return {
      id: r0,
      createdAt: r1,
      text: r2,
      language: r3,
      durationMs: r4,
      app: (flags & 1) !== 0 ? c.string.decode(state) : null
    }
  }
}

// @opennib/dictionary-entry
const encoding4 = {
  preencode(state, m) {
    c.string.preencode(state, m.id)
    c.string.preencode(state, m.term)
    state.end++ // max flag is 1 so always one byte

    if (m.replacement) c.string.preencode(state, m.replacement)
    c.uint.preencode(state, m.createdAt)
  },
  encode(state, m) {
    const flags = m.replacement ? 1 : 0

    c.string.encode(state, m.id)
    c.string.encode(state, m.term)
    c.uint.encode(state, flags)

    if (m.replacement) c.string.encode(state, m.replacement)
    c.uint.encode(state, m.createdAt)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      id: r0,
      term: r1,
      replacement: (flags & 1) !== 0 ? c.string.decode(state) : null,
      createdAt: c.uint.decode(state)
    }
  }
}

// @opennib/init-request
const encoding5 = {
  preencode(state, m) {
    c.string.preencode(state, m.historyDir)
    c.string.preencode(state, m.dictionaryDir)
  },
  encode(state, m) {
    c.string.encode(state, m.historyDir)
    c.string.encode(state, m.dictionaryDir)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.string.decode(state)

    return {
      historyDir: r0,
      dictionaryDir: r1
    }
  }
}

// @opennib/preload-request
const encoding6 = {
  preencode(state, m) {
    c.string.preencode(state, m.modelPath)
    c.string.preencode(state, m.language)
  },
  encode(state, m) {
    c.string.encode(state, m.modelPath)
    c.string.encode(state, m.language)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.string.decode(state)

    return {
      modelPath: r0,
      language: r1
    }
  }
}

// @opennib/transcribe-request
const encoding7 = {
  preencode(state, m) {
    c.buffer.preencode(state, m.samples)
    c.uint.preencode(state, m.sampleRate)
    c.uint.preencode(state, m.durationMs)
    c.string.preencode(state, m.modelPath)
    c.string.preencode(state, m.language)
  },
  encode(state, m) {
    c.buffer.encode(state, m.samples)
    c.uint.encode(state, m.sampleRate)
    c.uint.encode(state, m.durationMs)
    c.string.encode(state, m.modelPath)
    c.string.encode(state, m.language)
  },
  decode(state) {
    const r0 = c.buffer.decode(state)
    const r1 = c.uint.decode(state)
    const r2 = c.uint.decode(state)
    const r3 = c.string.decode(state)
    const r4 = c.string.decode(state)

    return {
      samples: r0,
      sampleRate: r1,
      durationMs: r2,
      modelPath: r3,
      language: r4
    }
  }
}

// @opennib/transcribe-file-request
const encoding8 = {
  preencode(state, m) {
    c.string.preencode(state, m.wavPath)
    c.string.preencode(state, m.model)
    c.string.preencode(state, m.language)
  },
  encode(state, m) {
    c.string.encode(state, m.wavPath)
    c.string.encode(state, m.model)
    c.string.encode(state, m.language)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.string.decode(state)
    const r2 = c.string.decode(state)

    return {
      wavPath: r0,
      model: r1,
      language: r2
    }
  }
}

// @opennib/text-response.error
const encoding9_0 = encoding1_0

// @opennib/text-response
const encoding9 = {
  preencode(state, m) {
    state.end++ // max flag is 2 so always one byte

    if (m.error) encoding9_0.preencode(state, m.error)
    if (m.text) c.string.preencode(state, m.text)
  },
  encode(state, m) {
    const flags = (m.error ? 1 : 0) | (m.text ? 2 : 0)

    c.uint.encode(state, flags)

    if (m.error) encoding9_0.encode(state, m.error)
    if (m.text) c.string.encode(state, m.text)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      error: (flags & 1) !== 0 ? encoding9_0.decode(state) : null,
      text: (flags & 2) !== 0 ? c.string.decode(state) : null
    }
  }
}

// @opennib/model-load-request
const encoding10 = {
  preencode(state, m) {
    c.string.preencode(state, m.model)
    c.string.preencode(state, m.language)
  },
  encode(state, m) {
    c.string.encode(state, m.model)
    c.string.encode(state, m.language)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.string.decode(state)

    return {
      model: r0,
      language: r1
    }
  }
}

// @opennib/cleaner-configure-request
const encoding11 = {
  preencode(state, m) {
    state.end++ // max flag is 1 so always one byte

    if (m.modelPath) c.string.preencode(state, m.modelPath)
  },
  encode(state, m) {
    const flags = m.modelPath ? 1 : 0

    c.uint.encode(state, flags)

    if (m.modelPath) c.string.encode(state, m.modelPath)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      modelPath: (flags & 1) !== 0 ? c.string.decode(state) : null
    }
  }
}

// @opennib/cleanup-request.terms
const encoding12_2 = c.array(c.frame(encoding4))

// @opennib/cleanup-request
const encoding12 = {
  preencode(state, m) {
    c.string.preencode(state, m.text)
    c.string.preencode(state, m.language)
    state.end++ // max flag is 1 so always one byte

    if (m.terms) encoding12_2.preencode(state, m.terms)
  },
  encode(state, m) {
    const flags = m.terms ? 1 : 0

    c.string.encode(state, m.text)
    c.string.encode(state, m.language)
    c.uint.encode(state, flags)

    if (m.terms) encoding12_2.encode(state, m.terms)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      text: r0,
      language: r1,
      terms: (flags & 1) !== 0 ? encoding12_2.decode(state) : null
    }
  }
}

// @opennib/history-append-request.entry
const encoding13_0 = c.frame(encoding3)

// @opennib/history-append-request
const encoding13 = {
  preencode(state, m) {
    encoding13_0.preencode(state, m.entry)
  },
  encode(state, m) {
    encoding13_0.encode(state, m.entry)
  },
  decode(state) {
    const r0 = encoding13_0.decode(state)

    return {
      entry: r0
    }
  }
}

// @opennib/history-list-request
const encoding14 = {
  preencode(state, m) {
    state.end++ // max flag is 2 so always one byte

    if (m.limit) c.uint.preencode(state, m.limit)
    if (m.before) c.string.preencode(state, m.before)
  },
  encode(state, m) {
    const flags = (m.limit ? 1 : 0) | (m.before ? 2 : 0)

    c.uint.encode(state, flags)

    if (m.limit) c.uint.encode(state, m.limit)
    if (m.before) c.string.encode(state, m.before)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      limit: (flags & 1) !== 0 ? c.uint.decode(state) : 0,
      before: (flags & 2) !== 0 ? c.string.decode(state) : null
    }
  }
}

// @opennib/history-list-response.error
const encoding15_0 = encoding1_0
// @opennib/history-list-response.entries
const encoding15_1 = c.array(c.frame(encoding3))

// @opennib/history-list-response
const encoding15 = {
  preencode(state, m) {
    state.end++ // max flag is 2 so always one byte

    if (m.error) encoding15_0.preencode(state, m.error)
    if (m.entries) encoding15_1.preencode(state, m.entries)
  },
  encode(state, m) {
    const flags = (m.error ? 1 : 0) | (m.entries ? 2 : 0)

    c.uint.encode(state, flags)

    if (m.error) encoding15_0.encode(state, m.error)
    if (m.entries) encoding15_1.encode(state, m.entries)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      error: (flags & 1) !== 0 ? encoding15_0.decode(state) : null,
      entries: (flags & 2) !== 0 ? encoding15_1.decode(state) : null
    }
  }
}

// @opennib/dictionary-list-response.error
const encoding16_0 = encoding1_0
// @opennib/dictionary-list-response.entries
const encoding16_1 = encoding12_2

// @opennib/dictionary-list-response
const encoding16 = {
  preencode(state, m) {
    state.end++ // max flag is 2 so always one byte

    if (m.error) encoding16_0.preencode(state, m.error)
    if (m.entries) encoding16_1.preencode(state, m.entries)
  },
  encode(state, m) {
    const flags = (m.error ? 1 : 0) | (m.entries ? 2 : 0)

    c.uint.encode(state, flags)

    if (m.error) encoding16_0.encode(state, m.error)
    if (m.entries) encoding16_1.encode(state, m.entries)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      error: (flags & 1) !== 0 ? encoding16_0.decode(state) : null,
      entries: (flags & 2) !== 0 ? encoding16_1.decode(state) : null
    }
  }
}

// @opennib/dictionary-remove-request
const encoding17 = {
  preencode(state, m) {
    c.string.preencode(state, m.id)
  },
  encode(state, m) {
    c.string.encode(state, m.id)
  },
  decode(state) {
    const r0 = c.string.decode(state)

    return {
      id: r0
    }
  }
}

// @opennib/model-progress
const encoding18 = {
  preencode(state, m) {
    c.string.preencode(state, m.model)
    c.uint.preencode(state, m.percent)
  },
  encode(state, m) {
    c.string.encode(state, m.model)
    c.uint.encode(state, m.percent)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.uint.decode(state)

    return {
      model: r0,
      percent: r1
    }
  }
}

// @opennib/dictate-request
const encoding19 = encoding8

function setVersion(v) {
  version = v
}

function encode(name, value, v = VERSION) {
  version = v
  return c.encode(getEncoding(name), value)
}

function decode(name, buffer, v = VERSION) {
  version = v
  return c.decode(getEncoding(name), buffer)
}

function getEnum(name) {
  switch (name) {
    default:
      throw new Error('Enum not found ' + name)
  }
}

function getEncoding(name) {
  switch (name) {
    case '@opennib/rpc-error':
      return encoding0
    case '@opennib/ack':
      return encoding1
    case '@opennib/empty':
      return encoding2
    case '@opennib/transcript-entry':
      return encoding3
    case '@opennib/dictionary-entry':
      return encoding4
    case '@opennib/init-request':
      return encoding5
    case '@opennib/preload-request':
      return encoding6
    case '@opennib/transcribe-request':
      return encoding7
    case '@opennib/transcribe-file-request':
      return encoding8
    case '@opennib/text-response':
      return encoding9
    case '@opennib/model-load-request':
      return encoding10
    case '@opennib/cleaner-configure-request':
      return encoding11
    case '@opennib/cleanup-request':
      return encoding12
    case '@opennib/history-append-request':
      return encoding13
    case '@opennib/history-list-request':
      return encoding14
    case '@opennib/history-list-response':
      return encoding15
    case '@opennib/dictionary-list-response':
      return encoding16
    case '@opennib/dictionary-remove-request':
      return encoding17
    case '@opennib/model-progress':
      return encoding18
    case '@opennib/dictate-request':
      return encoding19
    default:
      throw new Error('Encoder not found ' + name)
  }
}

function getStruct(name, v = VERSION) {
  const enc = getEncoding(name)
  return {
    preencode(state, m) {
      version = v
      enc.preencode(state, m)
    },
    encode(state, m) {
      version = v
      enc.encode(state, m)
    },
    decode(state) {
      version = v
      return enc.decode(state)
    }
  }
}

const resolveStruct = getStruct // compat

export { resolveStruct, getStruct, getEnum, getEncoding, encode, decode, setVersion, version }
